# bind prefix key to something sensible
unbind C-b
set-option -g prefix C-y
bind-key C-y send-prefix

# split panes using 'i' and 'k'
bind i split-window -h
bind k split-window -v
unbind '"'
unbind %

# change tabs with arrows
bind Left select-pane -L
bind Right select-pane -R
# change windows with ctrl-arrows
bind C-Left previous-window
bind C-Right next-window
# change sessions with ctrl-shift-arrows
bind C-S-Left switch-client -p
bind C-S-Right switch-client -n
# start index at 1
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

# join-pane
bind j   choose-window 'join-pane -h -s "%%"'
bind C-j choose-window 'join-pane    -s "%%"'

# neovim required settings
set-option -g focus-events on
set-option -sa terminal-features ',xterm-256color:RGB'
set -g status-interval 10
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavour 'macchiato'
# set catppuccin options
set -g @catppuccin_custom_plugin_dir "~/.tmux/modules/"
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator " | "

set -g @catppuccin_window_default_fill "none"
set -g @catppuccin_window_current_fill "all"

set -g @catppuccin_status_modules_right "application session date_time spotify_status"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"
set -g @catppuccin_date_time_text "%H:%M %d-%m-%Y"
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
