# bind prefix key to something sensible
unbind C-b
set-option -g prefix C-y
bind-key C-y send-prefix

# split panes using 'i' and 'k'
bind i split-window -h
bind k split-window -v
unbind '"'
unbind %

# change tabs with arrows
bind Left select-pane -L
bind Right select-pane -R
# change windows with ctrl-arrows
bind C-Left previous-window
bind C-Right next-window
# change sessions with ctrl-shift-arrows
bind C-S-Left switch-client -p
bind C-S-Right switch-client -n
# start index at 1
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

# join-pane
bind j   choose-window 'join-pane -h -s "%%"'
bind C-j choose-window 'join-pane    -s "%%"'

# neovim required settings
set-option -g focus-events on
set-option -sa terminal-features ',xterm-256color:RGB'
set -g status-interval 10
set -g @catppuccin_flavour 'mocha'
# set catppuccin options
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -ag status-right "#{E:@catppuccin_status_spotify_status}"
# List of plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tpm'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/catppuccin/tmux/catppuccin.tmux'
source "~/.tmux/modules/spotify_status.conf"
run '~/.tmux/plugins/tpm/tpm'
