%hidden MODULE_NAME="spotify_status"

set -og "@catppuccin_${MODULE_NAME}_icon" ' '
set -og "@catppuccin_${MODULE_NAME}_color" '#( [[ $(timeout 30 spotify_player get key playback | jq .is_playing) = "true" ]] && echo "#{E:@thm_green}" || echo "#{E:@thm_red}")'
set -og "@catppuccin_${MODULE_NAME}_text" " #(timeout 30 spotify_player get key playback | jq -r .item.name)"

source -F "~/.tmux/plugins/catppuccin/tmux/utils/status_module.conf"
