# vim:set ft=tmux:
%hidden MODULE_NAME="time"

set -ogq "@catppuccin_${MODULE_NAME}_icon" "󱑁 "
set -ogq "@catppuccin_${MODULE_NAME}_color" "#{E:@thm_blue}"
set -ogq "@catppuccin_${MODULE_NAME}_text" " #(date | awk '{ print $5,$6 }')"

source -F "#{d:current_file}/../plugins/catppuccin/tmux/utils/status_module.conf"
